# Password generated by Terraform, never typed or committed anywhere.
# Stored only in this project's local state file and in Key Vault.
resource "random_password" "postgres_admin" {
  length      = 32
  special     = true
  min_upper   = 2
  min_lower   = 2
  min_numeric = 2
  # Postgres connection strings choke on some special characters
  # (':', '/', '@', '?') when embedded directly in a URL -- restrict
  # to characters that are always URL-safe unescaped, rather than
  # writing URL-encoding logic just to work around this.
  override_special = "!#%^&*()-_=+"
}

resource "azurerm_postgresql_flexible_server" "main" {
  name                = "psql-${local.name_prefix}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  version  = "16" # matches the local pgvector/pgvector:pg16 Docker image (D-0004)
  sku_name = var.postgres_sku_name
  storage_mb = var.postgres_storage_mb

  administrator_login    = "overture_admin"
  administrator_password = random_password.postgres_admin.result

  # No high availability, no zone redundancy -- a portfolio demo
  # environment that gets destroyed at the end of every session has
  # no use for either, and both cost extra.
  #
  # No explicit `zone` pin either -- see decisions.md D-0030. An
  # explicit zone="1" caused an unexplained InternalServerError on
  # the first real apply in westus3; letting Azure choose a zone
  # automatically removes one concrete, plausible cause without
  # sacrificing anything this environment actually needs.

  tags = local.common_tags
}

# Allow-lists the pgvector extension at the server level. The actual
# `CREATE EXTENSION vector` still happens per-database -- Alembic
# migration 0002_add_chunks.py already does this (see its own
# comment about why CREATE EXTENSION is required even with the
# extension available at the server level).
resource "azurerm_postgresql_flexible_server_configuration" "vector_extension" {
  name      = "azure.extensions"
  server_id = azurerm_postgresql_flexible_server.main.id
  value     = "VECTOR"
}

resource "azurerm_postgresql_flexible_server_database" "overture" {
  name      = "overture"
  server_id = azurerm_postgresql_flexible_server.main.id
  collation = "en_US.utf8"
  charset   = "UTF8"
}

# Lets Aaron's laptop reach the server directly, to run `alembic
# upgrade head` and `overture extract` against it the same way he's
# been verifying every prior session's database work.
resource "azurerm_postgresql_flexible_server_firewall_rule" "allow_my_ip" {
  name             = "allow-my-ip"
  server_id        = azurerm_postgresql_flexible_server.main.id
  start_ip_address = var.my_ip_address
  end_ip_address   = var.my_ip_address
}

# The special 0.0.0.0-0.0.0.0 range is how Azure Postgres Flexible
# Server represents "allow other Azure services" -- needed in session
# 8 so the deployed Container App can reach this database. Harmless to
# create now; it has no effect until something inside Azure actually
# tries to connect.
resource "azurerm_postgresql_flexible_server_firewall_rule" "allow_azure_services" {
  name             = "allow-azure-services"
  server_id        = azurerm_postgresql_flexible_server.main.id
  start_ip_address = "0.0.0.0"
  end_ip_address   = "0.0.0.0"
}
