"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-22

Hand-written, not autogenerated -- there is no reachable Postgres
instance in the environment this was authored in. It was written to
match db/models.py column-for-column, but has NOT been proven against
a live database yet. That proof happens on Aaron's machine via
`alembic upgrade head` and gets logged in decisions.md once confirmed.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "discovery_sessions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("raw_transcript", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False, server_default="ingested"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "requirements",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("discovery_sessions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("span_start", sa.Integer(), nullable=False),
        sa.Column("span_end", sa.Integer(), nullable=False),
        sa.Column("span_text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False, server_default="1.0"),
    )
    op.create_index("ix_requirements_session_id", "requirements", ["session_id"])

    op.create_table(
        "solution_briefs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("discovery_sessions.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column("summary", sa.Text(), nullable=False, server_default=""),
    )

    op.create_table(
        "demo_configs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("discovery_sessions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("blueprint_id", sa.String(length=64), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False, server_default=""),
        sa.Column("tools", postgresql.ARRAY(sa.Text()), nullable=False, server_default="{}"),
        sa.Column("seed_corpus_ref", sa.String(length=255), nullable=True),
        sa.Column(
            "sample_questions", postgresql.ARRAY(sa.Text()), nullable=False, server_default="{}"
        ),
        sa.Column("token_budget", sa.Integer(), nullable=False, server_default="100000"),
        sa.Column("status", sa.String(length=32), nullable=False, server_default="draft"),
        sa.Column(
            "validation_errors", postgresql.ARRAY(sa.Text()), nullable=False, server_default="{}"
        ),
    )
    op.create_index("ix_demo_configs_session_id", "demo_configs", ["session_id"])


def downgrade() -> None:
    op.drop_table("demo_configs")
    op.drop_table("solution_briefs")
    op.drop_index("ix_requirements_session_id", table_name="requirements")
    op.drop_table("requirements")
    op.drop_table("discovery_sessions")
